export { callTool, createServer, main } from "./server"
export type { ServerDeps, ToolResult } from "./server"
export { BLOCKS, BLOCK_NAMES } from "./blocks"
export type { BlockInfo } from "./blocks"
export { guide } from "./guide"
export { pageHtml, embed } from "./page"
export type { PageOptions } from "./page"
export { writePage, openInBrowser } from "./open"
export type { WrittenPage } from "./open"
export { renderToContent, NO_BROWSER } from "./render"
export type { RenderedContent } from "./render"
export { outputRoot } from "./paths"
export { ensureHeadlessShell, awaitSetup } from "./browser"
export type { BrowserSetup } from "./browser"
export { closeBrowser } from "@ai-gui/image"
